export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const ADMIN_ALL_ORDERS_REQUEST = "ADMIN_ALL_ORDERS_REQUEST";
export const ADMIN_ALL_ORDERS_SUCCESS = "ADMIN_ALL_ORDERS_SUCCESS";
export const ADMIN_ALL_ORDERS_FAIL = "ADMIN_ALL_ORDERS_FAIL";

export const ADMIN_ORDER_DELETE_REQUEST = "ADMIN_ORDER_DELETE_REQUEST";
export const ADMIN_ORDER_DELETE_SUCCESS = "ADMIN_ORDER_DELETE_SUCCESS";
export const ADMIN_ORDER_DELETE_RESET = "ADMIN_ORDER_DELETE_RESET";
export const ADMIN_ORDER_DELETE_FAIL = "ADMIN_ORDER_DELETE_FAIL";

export const ADMIN_ORDER_UPDATE_REQUEST = "ADMIN_ORDER_UPDATE_REQUEST";
export const ADMIN_ORDER_UPDATE_SUCCESS = "ADMIN_ORDER_UPDATE_SUCCESS";
export const ADMIN_ORDER_UPDATE_RESET = "ADMIN_ORDER_UPDATE_RESET";
export const ADMIN_ORDER_UPDATE_FAIL = "ADMIN_ORDER_UPDATE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
