export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";


// Admin

export const ADMIN_USER_FETCH_REQUEST = "ADMIN_USER_FETCH_REQUEST";
export const ADMIN_USER_FETCH_FAIL = "ADMIN_USER_FETCH_FAIL";
export const ADMIN_USER_FETCH_SUCCESS = "ADMIN_USER_FETCH_SUCCESS";

export const ADMIN_USERDETAILS_FETCH_REQUEST = "ADMIN_USERDETAILS_FETCH_REQUEST";
export const ADMIN_USERDETAILS_FETCH_FAIL = "ADMIN_USERDETAILS_FETCH_FAIL";
export const ADMIN_USERDETAILS_FETCH_SUCCESS = "ADMIN_USERDETAILS_FETCH_SUCCESS";

export const ADMIN_USER_UPDATE_REQUEST = "ADMIN_USER_UPDATE_REQUEST";
export const ADMIN_USER_UPDATE_FAIL = "ADMIN_USER_UPDATE_FAIL";
export const ADMIN_USER_UPDATE_RESET = "ADMIN_USER_UPDATE_RESET";
export const ADMIN_USER_UPDATE_SUCCESS = "ADMIN_USER_UPDATE_SUCCESS";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_FAIL = "ADMIN_USER_DELETE_FAIL";
export const ADMIN_USER_DELETE_RESET = "ADMIN_USER_DELETE_RESET";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";