export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_ITEMS_REQUEST = "UPDATE_CART_ITEMS_REQUEST";
export const UPDATE_CART_ITEMS_SUCCESS = "UPDATE_CART_ITEMS_SUCCESS";
export const UPDATE_CART_ITEMS_FAIL = "UPDATE_CART_ITEMS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
